INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21398, '[question] How do you apply maintaining the expanded state of a group when the sort model changes for example?', 'https://github.com/mui/mui-x/issues/21398', 'mbiggs-gresham', 'https://github.com/mbiggs-gresham.png', '2026-02-19T14:14:42Z', '', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21398, 'Question', 'data-grid', 'High', 50, 'How do you apply maintaining the expanded state of a group when the sort model changes for example?', 'feature-request', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'Respond & Label', 'Thanks for reporting this, @mbiggs-gresham. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21397, '[data grid] Row grouping with a datasource doesn''t respect the order the rows are returned', 'https://github.com/mui/mui-x/issues/21397', 'mbiggs-gresham', 'https://github.com/mbiggs-gresham.png', '2026-02-19T14:05:51Z', '', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21397, 'Bug', 'data-grid', 'High', 70, 'Row grouping with a datasource doesn''t respect the order the rows are returned', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'Investigate & Fix', 'Thanks for reporting this, @mbiggs-gresham. This is a confirmed bug in how server-side row grouping handles re-fetched data after sort changes.

**Root cause:** When `keepChildrenExpanded` is active (default for grouped data), `handleGroupedDataUpdate` uses `updateRows()` which preserves the existing tree node order instead of respecting the new server-returned order. The flat data path correctly uses `setRows()` which does reorder.

**Workaround:** You can try setting `keepChildrenExpanded: false` on the data source to force the `setRows` path, though this will collapse expanded groups on sort.

We''ll work on a fix to properly handle row reordering in the grouped data update path.', '{"status": "done", "approach": "Traced server-side row grouping data flow: sortModelChange \u2192 debouncedFetchRows \u2192 handleGroupedDataUpdate \u2192 updateRows/updateNestedRows. Analyzed how row order is preserved in the tree.", "painPoints": "When keepChildrenExpanded is true (default for grouped data re-fetches), handleGroupedDataUpdate uses apiRef.current.updateRows() which performs insert/modify/delete operations. The tree preserves the original insertion order of children \u2014 updateRows modifies existing rows in-place without reordering them. The cache also stores responses keyed by params, but sorting order changes may hit stale cache entries.", "conclusion": "Bug confirmed. The root cause is in handleGroupedDataUpdate (useGridDataSourceBasePro.ts ~L342). When rows are re-fetched after a sort change, updateRows() preserves existing tree node order rather than respecting the new server-returned order. Additionally, the data source cache may serve stale pre-sort responses. The fix needs to either: (1) delete and re-insert rows to establish new order, or (2) clear cache on sort model change and use setRows path for grouped data.", "reasoning": "Server-side sorting means the server controls row order. When sortModel changes, fetchRows is called correctly, but the response handling in handleGroupedDataUpdate with keepChildrenExpanded=true calls updateRows which does not reorder existing nodes. The flat strategy (handleFlatDataUpdate) uses setRows which does respect order. The grouped strategy should do the same when sort changes.", "suggestedFix": "In handleGroupedDataUpdate, detect when the fetch was triggered by a sortModelChange (could pass a flag through fetchParams). When sorting changed, use the setRows path (keepChildrenExpanded=false behavior) instead of updateRows, or implement a reorder step after updateRows. Also ensure cache.clear() is called on sortModelChange for grouped data strategies.", "completedAt": "2026-02-19T21:13:53.971551+00:00"}');
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21329, '[data grid] Group row at bottom?', 'https://github.com/mui/mui-x/issues/21329', 'mbiggs-gresham', 'https://github.com/mbiggs-gresham.png', '2026-02-13T14:54:40Z', '', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21329, 'Bug', 'data-grid', 'High', 70, 'Group row at bottom?', 'feature-request', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'Investigate & Fix', 'Thanks for the suggestion, @mbiggs-gresham! This is a valid feature request for financial/reporting use cases.

**Current state:** The Data Grid''s row grouping always renders the group header row *above* its children. There''s an existing `footerId` concept in the tree node structure (used for aggregation footers), but no option to move the group row itself below its children.

**Feasibility:** This would require changes to the tree flattening logic (`getTreeNodeDescendants` in `gridRowsUtils.ts`) and the sorting/rendering pipeline to optionally place the group node after its children instead of before. For single-level grouping it''s more straightforward; multi-level adds complexity.

We''ve tracked this as a feature request. No ETA yet, but the architecture doesn''t fundamentally prevent it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21315, 'Grid selectors expect non-null apiRef', 'https://github.com/mui/mui-x/issues/21315', 'JohannesByle', 'https://github.com/JohannesByle.png', '2026-02-12T19:36:34Z', '', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21315, 'Bug', 'data-grid', 'High', 70, 'Grid selectors expect non-null apiRef', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'Investigate & Fix', 'Thanks for the detailed report, @JohannesByle. This is a confirmed v8 regression.

**Root cause:** `useGridApiRef()` in v8 returns a ref typed as `RefObject<GridApiCommunity | null>` (initialized to `null`), but `useGridSelector` and built-in selectors assume `apiRef.current` is non-null. When a custom component using selectors renders before the grid initializes, it crashes.

**Workaround:** Guard your selector usage:
```tsx
const count = apiRef.current ? gridFilteredTopLevelRowCountSelector(apiRef) : 0;
```

We''ll fix `useGridSelector` to handle the null case gracefully.', '{"status": "done", "approach": "Examined useGridApiRef (returns React.useRef(null)) and useGridSelector implementation. Checked how selectors access apiRef.current.state and apiRef.current.store.", "painPoints": "In v8, useGridApiRef() returns RefObject<GridApiCommunity | null> (initialized to null). But useGridSelector assumes apiRef.current is non-null \u2014 it calls apiRef.current.store.subscribe() and selector(apiRef) without null checks. When useGridSelector is called before the grid mounts (e.g., in a custom footer that renders before the grid initializes), it crashes with \"Cannot read properties of null\".", "conclusion": "Bug confirmed. The v8 migration changed useGridApiRef to explicitly type the ref as nullable (RefObject<GridApiCommunity | null>), but useGridSelector and the built-in selectors were not updated to handle the null case. The selectors directly access apiRef.current.state which throws when current is null.", "reasoning": "This is a type/runtime mismatch introduced in v8. The ref is correctly typed as nullable but consumers (useGridSelector, individual selectors like gridFilteredTopLevelRowCountSelector) assume non-null. The fix needs both: (1) useGridSelector should handle null apiRef.current gracefully (return a default/initial value), and (2) selector type signatures should accept nullable apiRef.", "suggestedFix": "In useGridSelector, add an early return with a default value when apiRef.current is null (before accessing .store or .state). For the subscribe callback, skip subscription when apiRef.current is null and re-subscribe when it becomes non-null. Update selector type signatures to accept RefObject<Api | null>. Consider adding a useSyncExternalStore getServerSnapshot that returns null/default for SSR safety too.", "completedAt": "2026-02-19T21:13:53.971551+00:00"}');
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21279, 'DataGrid exportState() does not include chartType', 'https://github.com/mui/mui-x/issues/21279', 'jamiedruce', 'https://github.com/jamiedruce.png', '2026-02-10T15:31:18Z', '', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21279, 'Bug', 'data-grid', 'High', 70, 'DataGrid exportState() does not include chartType', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'Investigate & Fix', 'Already resolved by @arminmeh. The `exportState()` intentionally stores chart configuration in a separate integration context key. Use `apiRef.current.restoreState(exportedState)` instead of passing to `initialState` — it handles both internal state and integration context.

See: https://github.com/mui/mui-x/issues/21279#issuecomment-3932291614', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21269, '[Server Side Tree][data grid] Unable to sort the table when the number of rows in the page is less than the number of rows per page', 'https://github.com/mui/mui-x/issues/21269', 'thomasmauriceco2ai', 'https://github.com/thomasmauriceco2ai.png', '2026-02-10T08:59:50Z', '', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21269, 'Bug', 'data-grid', 'High', 70, 'Unable to sort the table when the number of rows in the page is less than the number of rows per page', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: premium standard"]', 'Investigate & Fix', 'Thanks for reporting this, @thomasmauriceco2ai. This is a confirmed bug.

**Root cause:** When the sort model changes with server-side tree data, only root-level rows are re-fetched. Expanded child groups retain their cached (pre-sort) order because `sortModelChange` doesn''t trigger re-fetching of nested/child rows. When rows < pageSize, this is more visible because the entire dataset fits in one cache chunk.

**Workaround:** After changing the sort model, manually collapse and re-expand groups to trigger child re-fetching. Or set `dataSourceCache={null}` to disable caching (though this increases server calls).

We''ll fix this to re-fetch all expanded groups when the sort model changes.', '{"status": "done", "approach": "Analyzed the server-side tree data sorting flow. When sortingMode=\"server\", applySorting() in useGridSorting.ts skips client-side sorting and uses getTreeNodeDescendants to establish row order. Traced how sortModelChange triggers data re-fetch through the data source hooks.", "painPoints": "When rows < pageSize, the CacheChunkManager may produce different cache keys. The sort model change triggers debouncedFetchRows for the root level, but for tree data with nested rows, the child rows are fetched separately via fetchRowChildren. The cache key computation uses pagination params \u2014 when actual rows are fewer than pageSize, cache chunking may not align correctly, causing stale cached responses to be served instead of re-fetching.", "conclusion": "Bug confirmed. The issue is in the interaction between CacheChunkManager and the sort model. When rows < pageSize, the cache chunk spans the entire dataset in one chunk. On sortModelChange, the base data source hook calls debouncedFetchRows which re-fetches root rows. However, for server-side tree data, the sortModelChange event only triggers a root-level fetch \u2014 child rows are not automatically re-fetched. Combined with cache not being invalidated for sort changes on nested data, the tree retains old order.", "reasoning": "The sortModelChange handler in the base hook fires debouncedFetchRows() for standard strategies, but for tree data the nested rows (children) are managed separately. The cache stores responses keyed by (groupKeys + sortModel + pagination), so sort changes should produce new cache keys. The real issue is that only root-level rows are re-fetched on sort change \u2014 expanded children are not re-fetched, and their cached order persists.", "suggestedFix": "On sortModelChange for server-side tree data: (1) Clear the data source cache to invalidate stale sorted responses, (2) Re-fetch all currently expanded groups (not just root), similar to how filterModelChange should work. In useGridDataSourceBasePro, the sortModelChange event handler should trigger nestedDataManager.queue() for all expanded groups in addition to the root fetch.", "completedAt": "2026-02-19T21:13:53.971551+00:00"}');
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21053, '[tree view] lazy-loaded tree: auto-expand child nodes', 'https://github.com/mui/mui-x/issues/21053', 'caillou', 'https://github.com/caillou.png', '2026-01-23T14:49:58Z', '', '["status: waiting for maintainer", "scope: tree view", "support: pro standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21053, 'Bug', 'tree-view', 'High', 70, 'lazy-loaded tree: auto-expand child nodes', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["status: waiting for maintainer", "scope: tree view", "support: pro standard"]', 'Investigate & Fix', 'Thanks for the detailed report, @caillou. This is a valid enhancement request — auto-expanding lazy-loaded children when the response already includes nested sub-trees.

**Current limitation:** When `getTreeItems` returns nested children, the Tree View adds them to the tree but doesn''t auto-expand them. Calling `setItemExpansion` in `onExpandedItemsChange` triggers another fetch (as noted in #21088), creating a loop.

As @flaviendelangle mentioned, the two main approaches are:
1. `onItemsLazyLoaded` callback — gives full control over what to expand after a lazy load completes
2. `expandLazyLoadedItems` boolean — simpler but less flexible

The callback approach (option 1) seems more robust. It would need to expand items via an internal path that skips re-fetching (using the existing `setItemExpansionUnfiltered` method).', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21036, '[docs] MCP server mui-mcp does not support resource listing', 'https://github.com/mui/mui-x/issues/21036', 'f1eeman', 'https://github.com/f1eeman.png', '2026-01-23T12:08:40Z', '', '["docs", "status: waiting for maintainer", "scope: pickers", "support: docs-feedback"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21036, 'Bug', 'pickers', 'High', 50, 'MCP server mui-mcp does not support resource listing', 'docs', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["docs", "status: waiting for maintainer", "scope: pickers", "support: docs-feedback"]', 'Respond & Label', 'Thanks for reporting this, @f1eeman. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (20989, '[data grid] Screen reader over-reads DOM after rowReordering live region announcement', 'https://github.com/mui/mui-x/issues/20989', 'rhysmitchell', 'https://github.com/rhysmitchell.png', '2026-01-21T09:41:25Z', '', '["scope: data grid", "status: waiting for maintainer"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (20989, 'Bug', 'data-grid', 'High', 70, 'Screen reader over-reads DOM after rowReordering live region announcement', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer"]', 'Investigate & Fix', 'Thanks for reporting this accessibility issue, @rhysmitchell.

**Analysis:** The issue is likely caused by the custom `aria-live="assertive"` live region triggering NVDA to re-read the DOM context. When the grid DOM mutates during row reordering (rows physically move in the DOM due to virtualization updates), NVDA interprets the DOM changes as new content and reads them.

**Recommendations:**
1. Use `aria-live="polite"` instead of `assertive` — polite waits for the user to be idle
2. Use `aria-atomic="true"` on the live region so only the region''s content is announced, not surrounding DOM
3. Ensure the live region is outside the grid''s DOM tree to avoid NVDA reading grid mutations as part of the announcement
4. Add a small delay (e.g., `setTimeout` 100ms) before updating the live region text, so the DOM mutation settles first

This appears to be an NVDA-specific behavior with `assertive` live regions during DOM mutations.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (20970, '[data grid] Grouping with checkbox selection and server-side-data', 'https://github.com/mui/mui-x/issues/20970', 'leonhardanthony', 'https://github.com/leonhardanthony.png', '2026-01-19T14:18:54Z', '', '["scope: data grid", "status: waiting for maintainer", "feature: Selection", "feature: Server integration", "support: premium standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (20970, 'Feature', 'data-grid', 'High', 50, 'Grouping with checkbox selection and server-side-data', 'feature-request', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "feature: Selection", "feature: Server integration", "support: premium standard"]', 'Respond & Label', 'Thanks for reporting this, @leonhardanthony. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21376, 'DataGrid CSP Error: Emotion CacheProvider nonce is not used in inline styles', 'https://github.com/mui/mui-x/issues/21376', 'visualjerk', 'https://github.com/visualjerk.png', '2026-02-18T10:43:09Z', '', '["scope: data grid", "status: waiting for maintainer", "support: pro standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21376, 'Bug', 'data-grid', 'Medium', 50, 'DataGrid CSP Error: Emotion CacheProvider nonce is not used in inline styles', 'security', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: pro standard"]', 'Investigate & Fix', 'Thanks for reporting this, @visualjerk. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21357, '[data grid] getRowId prop does not work with server-side tree data', 'https://github.com/mui/mui-x/issues/21357', 'ahmedBilal5', 'https://github.com/ahmedBilal5.png', '2026-02-17T10:55:27Z', '', '["scope: data grid", "status: waiting for maintainer", "support: pro standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21357, 'Bug', 'data-grid', 'Medium', 70, 'getRowId prop does not work with server-side tree data', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: pro standard"]', 'Investigate & Fix', 'Thanks for reporting this, @ahmedBilal5. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21347, 'DataGridPro TreeData: “inside” Drop Not Triggered When Initial Data Contains No Child Nodes', 'https://github.com/mui/mui-x/issues/21347', 'Abassion', 'https://github.com/Abassion.png', '2026-02-16T12:48:58Z', '', '["scope: data grid", "status: waiting for maintainer", "support: pro standard"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21347, 'Bug', 'data-grid', 'Medium', 70, 'DataGridPro TreeData: “inside” Drop Not Triggered When Initial Data Contains No Child Nodes', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: pro standard"]', 'Investigate & Fix', 'Thanks for reporting this, @Abassion. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21379, '[charts] Warn users when the controlled tooltip does not match the trigger', 'https://github.com/mui/mui-x/issues/21379', 'alexfauquette', 'https://github.com/alexfauquette.png', '2026-02-18T14:00:30Z', '', '["status: waiting for maintainer", "scope: charts"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21379, 'Bug', 'charts', 'Low', 70, 'Warn users when the controlled tooltip does not match the trigger', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["status: waiting for maintainer", "scope: charts"]', 'Investigate & Fix', 'Thanks for reporting this, @alexfauquette. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21368, 'ajv has ReDoS when using `$data` option', 'https://github.com/mui/mui-x/issues/21368', 'damiangreen', 'https://github.com/damiangreen.png', '2026-02-18T06:58:38Z', '', '["scope: data grid", "status: waiting for maintainer", "scope: pickers", "scope: tree view", "scope: charts"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21368, 'Bug', 'data-grid', 'Low', 50, 'ajv has ReDoS when using `$data` option', 'security', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "scope: pickers", "scope: tree view", "scope: charts"]', 'Investigate & Fix', 'Thanks for reporting this, @damiangreen. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21320, '[docs] Demo TreeDataSyncRowData crashes', 'https://github.com/mui/mui-x/issues/21320', 'Abassion', 'https://github.com/Abassion.png', '2026-02-13T09:14:15Z', '', '["docs", "scope: data grid", "status: waiting for maintainer"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21320, 'Bug', 'data-grid', 'Low', 50, 'Demo TreeDataSyncRowData crashes', 'docs', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["docs", "scope: data grid", "status: waiting for maintainer"]', 'Respond & Label', 'Thanks for reporting this, @Abassion. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21318, '[charts-pro] GHSA-w7fw-mjwx-w883 vulnerability', 'https://github.com/mui/mui-x/issues/21318', 'damiangreen', 'https://github.com/damiangreen.png', '2026-02-13T02:22:39Z', '', '["status: waiting for maintainer", "scope: charts"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21318, 'Bug', 'charts', 'Low', 50, 'GHSA-w7fw-mjwx-w883 vulnerability', 'security', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["status: waiting for maintainer", "scope: charts"]', 'Investigate & Fix', 'Thanks for reporting this, @damiangreen. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21314, 'Datagrid, saving a view with reorganize columns, filter and grouping does not work', 'https://github.com/mui/mui-x/issues/21314', 'datalogyinc-cloud', 'https://github.com/datalogyinc-cloud.png', '2026-02-12T18:00:59Z', '', '["scope: data grid", "status: waiting for maintainer"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21314, 'Bug', 'data-grid', 'Low', 70, 'Datagrid, saving a view with reorganize columns, filter and grouping does not work', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer"]', 'Investigate & Fix', 'Thanks for reporting this, @datalogyinc-cloud. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21310, '[question] Breaking on upgrading version from 8.9.2 to latest version', 'https://github.com/mui/mui-x/issues/21310', 'Harshit-lawcus', 'https://github.com/Harshit-lawcus.png', '2026-02-12T14:00:25Z', '', '["scope: data grid", "status: waiting for maintainer", "support: unknown"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21310, 'Question', 'data-grid', 'Low', 50, 'Breaking on upgrading version from 8.9.2 to latest version', 'feature-request', '{"hasReproSteps": false, "hasVersion": true, "hasExpectedBehavior": false, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer", "support: unknown"]', 'Respond & Label', 'Thanks for reporting this, @Harshit-lawcus. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21304, 'DataGrid: Styles in sx selector .MuiDataGrid-menu are not applied to column menu (cannot change zIndex)', 'https://github.com/mui/mui-x/issues/21304', 'dcoates83', 'https://github.com/dcoates83.png', '2026-02-11T20:26:28Z', '', '["scope: data grid", "status: waiting for maintainer"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21304, 'Bug', 'data-grid', 'Low', 70, 'DataGrid: Styles in sx selector .MuiDataGrid-menu are not applied to column menu (cannot change zIndex)', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["scope: data grid", "status: waiting for maintainer"]', 'Investigate & Fix', 'Thanks for reporting this, @dcoates83. We''ll look into it.', NULL);
INSERT OR REPLACE INTO issues (number, title, url, author, author_avatar, created_at, body, labels, status)
VALUES (21278, '[pickers] using date-fns adapter with time format KK (Hour [0-11]) does not display properly', 'https://github.com/mui/mui-x/issues/21278', 'rvspin', 'https://github.com/rvspin.png', '2026-02-10T15:06:10Z', '', '["status: waiting for maintainer", "scope: pickers"]', 'pending');
INSERT OR REPLACE INTO triage_analysis (issue_number, type, component, priority, completeness, summary, classification, checklist, suggested_labels, suggested_action, suggested_comment, investigation)
VALUES (21278, 'Bug', 'pickers', 'Low', 70, 'using date-fns adapter with time format KK (Hour [0-11]) does not display properly', 'bug', '{"hasReproSteps": true, "hasVersion": true, "hasExpectedBehavior": true, "hasEnvironment": true, "hasScreenshot": false}', '["status: waiting for maintainer", "scope: pickers"]', 'Investigate & Fix', 'Thanks for reporting this, @rvspin. We''ll look into it.', NULL);